#!/bin/bash

# Install: sudo make install

# TODO ne pas enchaîner les fetch
# TODO proposer Yes/No de résoudre certains pb ?
# TODO merge d'une feature
# TODO merge auto multi features
# TODO doc author ?
# TODO couplage options_handler::require_parameter() avec usage()
# TODO ui.inc.sh pas assez sûr niveau collision de noms...
# camelCase et autre_notation en même temps...
# TODO créer une branche stable ?

if [ "$DEBUG" = "1" ]; then
	set -x
fi

# Includes :
. `dirname $0`/conf/config.inc.sh
. $TWGIT_INC_DIR/common.inc.sh

##
# Affiche l'aide
#
function usage () {
	echo; help 'Usage:'
	help_detail 'twgit <command> [<action>]'
	help_detail '    Always provide branch names without prefix:'
	help_detail "    - '$TWGIT_PREFIX_FEATURE', '$TWGIT_PREFIX_RELEASE', '$TWGIT_PREFIX_HOTFIX', (tag) '$TWGIT_PREFIX_TAG'"

	echo; help 'Available commands are:'
	help_detail '<b>feature</b>   Manage your feature branches.'
	help_detail '<b>release</b>   Manage your release branches.'
	help_detail '<b>hotfix</b>    Manage your hotfix branches.'
	help_detail '<b>tag</b>       Manage your tags.'
	help_detail '<b>[help]</b>    Display this help.'
	echo; help 'See also:'
	help_detail "Try 'twgit <command> [help]' for more details."
	echo
}

##
# Appelle l'action demandée ("cmd_$2") sur la commande spécifiée ($1).
# Les paramètres surnumérères sont passés à la commande.
#
# @param string $1 commande demandée
# @param string $2 nom de l'action demandée, 'help' par défaut
#
function main () {
	if [ $# -lt 1 ]; then
		usage
		exit 1
	fi

	# load command:
	if [ ! -z "$1" ]; then
		local command="$1"; shift
		local command_file="$TWGIT_INC_DIR/twgit_$command.inc.sh";
		if [ "$command" = 'help' ]; then
			usage
			exit 0
		elif [ ! -e "$command_file" ]; then
			error "Command not found: '$command'"
			usage
			exit 1
		else
			. "$command_file"
		fi
	fi

	# run the specified action:
	local action='help'
	if [ ! -z "$1" ]; then
		action="$1"; shift
	fi
	local action_func_name="cmd_$action"
	if ! type "$action_func_name" >/dev/null 2>&1; then
		error "Unknown action: '$action'"
		usage
		exit 1
	else
		$action_func_name "$@"
	fi
}

assert_git_configured
main "$@"
